//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReShadeDeployer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReShadeDeployer.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}
        ///
        ///Copyright © 2024 Jobus
        ///https://github.com/Jobus0/reshade-deployer.
        /// </summary>
        public static string About_Info {
            get {
                return ResourceManager.GetString("About_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction failed because write-access was denied. Exit all other programs that use ReShade and try again..
        /// </summary>
        public static string AccessError {
            get {
                return ResourceManager.GetString("AccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction Failed.
        /// </summary>
        public static string AccessError_Title {
            get {
                return ResourceManager.GetString("AccessError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-on Support.
        /// </summary>
        public static string Addon {
            get {
                return ResourceManager.GetString("Addon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this if you plan to install a ReShade add-on to the game.
        ///
        ///Warning: Intended for singleplayer games only and may cause bans in multiplayer games..
        /// </summary>
        public static string Addon_Tooltip {
            get {
                return ResourceManager.GetString("Addon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Exit On Deploy.
        /// </summary>
        public static string AlwaysExitOnDeploy {
            get {
                return ResourceManager.GetString("AlwaysExitOnDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always exit the program after deploying ReShade without asking..
        /// </summary>
        public static string AlwaysExitOnDeploy_Tooltip {
            get {
                return ResourceManager.GetString("AlwaysExitOnDeploy_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade website (https://reshade.me) is down or the connection was blocked..
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        public static string ConnectionError_Title {
            get {
                return ResourceManager.GetString("ConnectionError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu Deploy.
        /// </summary>
        public static string ContextMenuDeploy {
            get {
                return ResourceManager.GetString("ContextMenuDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a &apos;Deploy ReShade&apos; option to the exe context (right-click) menu..
        /// </summary>
        public static string ContextMenuDeploy_Tooltip {
            get {
                return ResourceManager.GetString("ContextMenuDeploy_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like the target application uses DirectX 8.
        ///
        ///In order to use ReShade you&apos;ll have to download an additional wrapper from d3d8to9 which converts all API calls to DirectX 9.
        ///
        ///https://github.com/crosire/d3d8to9/releases.
        /// </summary>
        public static string D3D8_Info {
            get {
                return ResourceManager.GetString("D3D8_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy To Game.
        /// </summary>
        public static string DeployButton {
            get {
                return ResourceManager.GetString("DeployButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy To {0}.
        /// </summary>
        public static string DeployButton_Targeted {
            get {
                return ResourceManager.GetString("DeployButton_Targeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you have picked the correct Target API above first.
        ///
        ///If you are unsure, check the API section of the game&apos;s PCGamingWiki page..
        /// </summary>
        public static string DeployButton_Tooltip {
            get {
                return ResourceManager.GetString("DeployButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade was successfully deployed!.
        /// </summary>
        public static string DeploySuccess {
            get {
                return ResourceManager.GetString("DeploySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string DeploySuccess_Title {
            get {
                return ResourceManager.GetString("DeploySuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectX 10 or later.
        /// </summary>
        public static string DirectX10 {
            get {
                return ResourceManager.GetString("DirectX10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dxgi.dll.
        /// </summary>
        public static string DirectX10_Tooltip {
            get {
                return ResourceManager.GetString("DirectX10_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectX 9.
        /// </summary>
        public static string DirectX9 {
            get {
                return ResourceManager.GetString("DirectX9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d3d9.dll.
        /// </summary>
        public static string DirectX9_Tooltip {
            get {
                return ResourceManager.GetString("DirectX9_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access &apos;{0}&apos;. Try again later, or please report to the developer..
        /// </summary>
        public static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed.
        /// </summary>
        public static string DownloadError_Title {
            get {
                return ResourceManager.GetString("DownloadError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade Deployer will now download ReShade and set up the required folder structure into the current folder.
        ///
        ///This includes the Shaders and Textures folders, where you will place your shader and texture files.
        ///
        ///If you wish to keep these files elsewhere, press &apos;Exit&apos; and move the program first..
        /// </summary>
        public static string FirstTimeSetup {
            get {
                return ResourceManager.GetString("FirstTimeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First-Time Setup.
        /// </summary>
        public static string FirstTimeSetup_Title {
            get {
                return ResourceManager.GetString("FirstTimeSetup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the game&apos;s runtime executable..
        /// </summary>
        public static string OpenFileDialog_Title {
            get {
                return ResourceManager.GetString("OpenFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenGL.
        /// </summary>
        public static string OpenGL {
            get {
                return ResourceManager.GetString("OpenGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opengl32.dll.
        /// </summary>
        public static string OpenGL_Tooltip {
            get {
                return ResourceManager.GetString("OpenGL_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShadePreset.ini already exists.
        ///
        ///Would you like to overwrite it?.
        /// </summary>
        public static string PresetOverwrite {
            get {
                return ResourceManager.GetString("PresetOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, keep old file.
        /// </summary>
        public static string PresetOverwrite_No {
            get {
                return ResourceManager.GetString("PresetOverwrite_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Preset.
        /// </summary>
        public static string PresetOverwrite_Title {
            get {
                return ResourceManager.GetString("PresetOverwrite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, overwrite file.
        /// </summary>
        public static string PresetOverwrite_Yes {
            get {
                return ResourceManager.GetString("PresetOverwrite_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Game.
        /// </summary>
        public static string SelectGameButton {
            get {
                return ResourceManager.GetString("SelectGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target API.
        /// </summary>
        public static string TargetAPI {
            get {
                return ResourceManager.GetString("TargetAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the rendering API that the game uses.
        ///
        ///When selecting a game, the executable will be scanned to try to automatically select the correct API.
        ///
        ///Otherwise, if you are unsure, check the API section of the game&apos;s PCGamingWiki page..
        /// </summary>
        public static string TargetAPI_Tooltip {
            get {
                return ResourceManager.GetString("TargetAPI_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string UninstallDeployer {
            get {
                return ResourceManager.GetString("UninstallDeployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all registry entries of ReShade Deployer and delete the system-wide Vulkan ReShade layer.
        ///
        ///This is recommended if you want to stop using ReShade Deployer and go back to the official installer..
        /// </summary>
        public static string UninstallDeployer_Content {
            get {
                return ResourceManager.GetString("UninstallDeployer_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update of ReShade Deployer is available!
        ///
        ///New version: {0}
        ///Current version: {1}
        ///
        ///Would you like to install it?
        ///
        ///Changelog is available here:
        ///https://github.com/Jobus0/ReShade-Deployer/releases.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string UpdateAvailable_Title {
            get {
                return ResourceManager.GetString("UpdateAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateDeployer {
            get {
                return ResourceManager.GetString("UpdateDeployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already on the latest version..
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globally update your ReShade DLL files to the latest version..
        /// </summary>
        public static string UpdateReShade_Tooltip {
            get {
                return ResourceManager.GetString("UpdateReShade_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade version:.
        /// </summary>
        public static string VersionPrefix {
            get {
                return ResourceManager.GetString("VersionPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulkan.
        /// </summary>
        public static string Vulkan {
            get {
                return ResourceManager.GetString("Vulkan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to install ReShade with Add-on Support for Vulkan globally.
        ///
        ///Be aware of ban risks if you play an online game using Vulkan that you have deployed ReShade to before.
        ///
        ///To be safe, press Cancel and uncheck Add-on Support before deploying again..
        /// </summary>
        public static string Vulkan_Addon_Warning {
            get {
                return ResourceManager.GetString("Vulkan_Addon_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates no DLL in the game directory, but installs ReShade to Vulkan system-wide instead..
        /// </summary>
        public static string Vulkan_Tooltip {
            get {
                return ResourceManager.GetString("Vulkan_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
